# Generated by Django 2.2.8 on 2019-12-30 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalAudio',
            fields=[
                ('additional_audio_index', models.IntegerField(primary_key=True, serialize=False)),
                ('ojibwe', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('regular', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='Regular File')),
                ('mobile', models.CharField(default='', max_length=200, verbose_name='Mobile File')),
            ],
        ),
        migrations.CreateModel(
            name='AudioForBasicForm',
            fields=[
                ('audio_for_basic_forms_index', models.IntegerField(primary_key=True, serialize=False)),
                ('ojibwe', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentCollection',
            fields=[
                ('url', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('copyright', models.CharField(blank=True, max_length=200, null=True, verbose_name='Copyright')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='Description')),
                ('body', models.TextField(blank=True, default='', null=True, verbose_name='Document Body')),
                ('bibliography', models.TextField(blank=True, default='', null=True, verbose_name='Bibliography')),
            ],
        ),
        migrations.CreateModel(
            name='HistorySet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('src', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('alt', models.CharField(default='', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageCollection',
            fields=[
                ('url', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('copyright', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mainimage', to='dictionary.Image')),
                ('thumb', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dictionary.Image')),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('description', models.TextField()),
                ('distinguisher', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('pos', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KeywordGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('keyword', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dictionary.Keyword')),
            ],
        ),
        migrations.CreateModel(
            name='MainEntry',
            fields=[
                ('url', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('old_url', models.CharField(max_length=200)),
                ('head_lemma', models.CharField(blank=True, max_length=200, null=True, verbose_name='Lemma')),
                ('notes', models.TextField(blank=True, default='', null=True)),
                ('gloss', models.TextField(blank=True, default='', null=True)),
                ('word_parts', models.TextField(blank=True, default='', null=True)),
                ('reduplication', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('stem', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('indexed', models.BooleanField()),
                ('head_audio', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='dictionary.Audio', verbose_name='Main Audio')),
                ('head_image', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='dictionary.Image', verbose_name='Main Image')),
            ],
            options={
                'verbose_name': 'Main Entry',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('date', models.CharField(max_length=200, verbose_name='Date')),
                ('html', models.TextField(default='', verbose_name='Content')),
            ],
        ),
        migrations.CreateModel(
            name='PartOfSpeech',
            fields=[
                ('abbrev', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Abbreviation')),
                ('full', models.CharField(max_length=200, verbose_name='Full Name')),
                ('description', models.TextField(default='')),
                ('section_url', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Full Name')),
            ],
        ),
        migrations.CreateModel(
            name='Poss',
            fields=[
                ('abbrev', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('full', models.CharField(default='', max_length=200)),
            ],
            options={
                'verbose_name': 'Inflectional Attributes',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('abbrev', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('full', models.CharField(default='', max_length=200)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='SentenceExample',
            fields=[
                ('sentence_examples_index', models.IntegerField(primary_key=True, serialize=False)),
                ('ojibwe', models.TextField(blank=True, default='', null=True)),
                ('english', models.TextField(blank=True, default='', null=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sentence_examples', to='dictionary.MainEntry')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('src', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('thumb', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dictionary.Image')),
            ],
        ),
        migrations.CreateModel(
            name='VideoCollection',
            fields=[
                ('url', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('copyright', models.CharField(blank=True, max_length=200, null=True, verbose_name='Copyright')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('thumb', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dictionary.Image')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dictionary.Video', verbose_name='Video')),
            ],
        ),
        migrations.CreateModel(
            name='WordFamily',
            fields=[
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='head_inv', serialize=False, to='dictionary.MainEntry')),
            ],
        ),
        migrations.CreateModel(
            name='WordPart',
            fields=[
                ('url', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('old_url', models.CharField(max_length=200)),
                ('title', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('type', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('gloss', models.TextField(blank=True, default='', null=True)),
                ('subtypes', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('variants', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('words_that_use_this_part', models.ManyToManyField(to='dictionary.MainEntry')),
            ],
            options={
                'verbose_name': 'Word Part Entry',
            },
        ),
        migrations.CreateModel(
            name='VideoResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('righttext', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dictionary.Image')),
                ('righthref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dictionary.VideoCollection')),
                ('url', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dictionary.MainEntry')),
            ],
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('href', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('initials', models.CharField(max_length=30)),
                ('primary_name', models.CharField(max_length=200, verbose_name='Primary Name')),
                ('ojibwe_name', models.CharField(default='', max_length=200, verbose_name='Ojibwe Name')),
                ('english_name', models.CharField(default='', max_length=200, verbose_name='English Name')),
                ('community', models.CharField(default='', max_length=200, verbose_name='Community')),
                ('region', models.CharField(default='', max_length=200, verbose_name='Region')),
                ('description', models.TextField(default='')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dictionary.Image')),
            ],
        ),
        migrations.CreateModel(
            name='SentenceExampleAudioRec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='dictionary.Audio')),
                ('sentence_examples_index', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audio_rec', to='dictionary.SentenceExample')),
                ('speaker', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='dictionary.Speaker')),
            ],
            options={
                'verbose_name': 'Sentence Example Audio and Speaker',
            },
        ),
        migrations.CreateModel(
            name='RelatedWord',
            fields=[
                ('title', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('word', models.ManyToManyField(to='dictionary.MainEntry')),
            ],
        ),
        migrations.AddField(
            model_name='mainentry',
            name='head_speaker',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='dictionary.Speaker', verbose_name='Main Speaker'),
        ),
        migrations.AddField(
            model_name='mainentry',
            name='history_set',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='dictionary.HistorySet'),
        ),
        migrations.AddField(
            model_name='mainentry',
            name='keyword_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dictionary.KeywordGroup', verbose_name='Keyword Group'),
        ),
        migrations.AddField(
            model_name='mainentry',
            name='paired_with',
            field=models.ManyToManyField(blank=True, default='', related_name='paired_with_inv', to='dictionary.MainEntry', verbose_name='Paired With'),
        ),
        migrations.AddField(
            model_name='mainentry',
            name='part_of_speech',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dictionary.PartOfSpeech', verbose_name='Part Of Speech'),
        ),
        migrations.AddField(
            model_name='mainentry',
            name='redirect',
            field=models.ManyToManyField(blank=True, default='', related_name='redirect_inv', to='dictionary.MainEntry', verbose_name='Redirect to'),
        ),
        migrations.AddField(
            model_name='mainentry',
            name='region',
            field=models.ManyToManyField(blank=True, to='dictionary.Region'),
        ),
        migrations.AddField(
            model_name='mainentry',
            name='related_words',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dictionary.RelatedWord'),
        ),
        migrations.AddField(
            model_name='mainentry',
            name='see_also',
            field=models.ManyToManyField(blank=True, default='', related_name='see_also_inv', to='dictionary.MainEntry', verbose_name='See Also'),
        ),
        migrations.CreateModel(
            name='InflectionalForm',
            fields=[
                ('inflectional_forms_index', models.IntegerField(primary_key=True, serialize=False)),
                ('form', models.CharField(blank=True, max_length=200, null=True)),
                ('poss', models.ManyToManyField(blank=True, to='dictionary.Poss')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dictionary.MainEntry')),
            ],
        ),
        migrations.CreateModel(
            name='ImageResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('righttext', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dictionary.Image')),
                ('righthref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dictionary.ImageCollection')),
                ('url', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dictionary.MainEntry')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('historic_entry', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('creation_datetime', models.DateTimeField()),
                ('HistorySet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dictionary.HistorySet')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('righttext', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('righthref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dictionary.DocumentCollection')),
                ('url', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dictionary.MainEntry')),
            ],
        ),
        migrations.CreateModel(
            name='AudioForBasicFormAudioRec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='dictionary.Audio')),
                ('audio_for_basic_forms_index', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audio_rec', to='dictionary.AudioForBasicForm')),
                ('speaker', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='dictionary.Speaker')),
            ],
            options={
                'verbose_name': 'Basic Form Audio and Speaker',
            },
        ),
        migrations.AddField(
            model_name='audioforbasicform',
            name='entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='basic_audio', to='dictionary.MainEntry'),
        ),
        migrations.AddField(
            model_name='audioforbasicform',
            name='poss',
            field=models.ManyToManyField(blank=True, to='dictionary.Poss'),
        ),
        migrations.CreateModel(
            name='AdditionalAudioAudioRec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_audio_index', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audio_rec', to='dictionary.AdditionalAudio')),
                ('audio', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='dictionary.Audio')),
                ('speaker', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='dictionary.Speaker')),
            ],
            options={
                'verbose_name': 'Additional Form Audio and Speaker',
            },
        ),
        migrations.AddField(
            model_name='additionalaudio',
            name='entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='additional_audio', to='dictionary.MainEntry'),
        ),
        migrations.AddField(
            model_name='additionalaudio',
            name='poss',
            field=models.ManyToManyField(blank=True, to='dictionary.Poss'),
        ),
        migrations.CreateModel(
            name='WordFamilyPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(default='', max_length=200)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='dictionary.MainEntry')),
                ('word_family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='dictionary.WordFamily')),
            ],
        ),
        migrations.AddField(
            model_name='mainentry',
            name='word_family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dictionary.WordFamily'),
        ),
    ]
