# Generated by Django 2.2.8 on 2019-12-30 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyset',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mainentry',
            name='history_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dictionary.HistorySet'),
        ),
    ]
