# Generated by Django 2.2.5 on 2019-10-16 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainentry',
            name='word_family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dictionary.WordFamily'),
        ),
        migrations.AlterField(
            model_name='mainentry',
            name='related_words',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dictionary.RelatedWord'),
        ),
    ]
