# Generated by Django 2.2.5 on 2019-10-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_auto_20191016_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatedword',
            name='word',
        ),
        migrations.AddField(
            model_name='relatedword',
            name='word',
            field=models.ManyToManyField(to='dictionary.MainEntry'),
        ),
    ]
