# Generated by Django 2.2.5 on 2019-10-17 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0004_keyword_keywordgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainentry',
            name='keyword_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dictionary.KeywordGroup'),
        ),
    ]
