# Generated by Django 2.2.5 on 2019-10-17 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0005_mainentry_keyword_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='distinguisher',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='pos',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
