# Generated by Django 2.2.5 on 2019-10-17 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0007_auto_20191017_0357'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordpart',
            name='variants',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
